### ISSUE TITLE
Waiting on multiple workflow runs before the current one

### ISSUE THREAD

**Issue by praneetloke** [softprops/turnstyle#3]
First off, thank you for making this Action! I wish GH would make this a built-in feature and provide an option for Batched CI especially given that is based on top of Azure Pipelines runners.

Is there a reason why the action only awaits a single in-progress workflow run rather than all of the ones that are ahead of it in the queue? Particularly, this [line](https://github.com/softprops/turnstyle/blob/master/src/main.ts#L28). I am seeing a situation where multiple PRs closed in rapid succession can cause n-1 of those to wait on just one workflow run, which when that completes all of the awaited runs then resume execution at the same time -- the exact situation that I hoped this action would prevent. Am I missing something here?

**Comment by softprops** [comment]
> thank you for making this Action

Thanks for the kind words. I appreciate that.

>  I am seeing a situation where multiple PRs closed in rapid succession can cause n-1 of those to wait on just one workflow run, which when that completes all of the awaited runs then resume execution at the same time -- the exact situation that I hoped this action would prevent. Am I missing something here?

Let's say there are three workflow runs all triggered around the same time. I'll call these 1, 2, 3. Though githubs workflow runs execute asyncronously they are assigned an auto incrementing id. This plugin leverages that to understand, given the current set of runs for a workflow, what the previous active run to check is. 

Let's say 1, 2, 3 runs are active. 

1 sees no active runs that have a run id less than it's own so it proceeds. 2 and 3 both see 1 is in flight so they wait. 

1 completes. 2 and 3 both query for active runs. 2 can see there are no active runs with a run id less that 2 so it proceeds. 3 sees there is an active run with a run id less than 3 so it waits.

2 completes. 3 queries for active run ids. It sees there is no active run with a run ids less that three so it proceeds. 

The idea here is that runs always check for active runs with run ids less than it's own before moving forward. GitHub will manage the auto increment id for you so no external storage locking is needed.

This is essentially what you want if you are building a continuous deployment pipeline and need to synchronize workflow runs so that you don't end up with multiple deployments for the same service interfering with each other. That's the usecase this action targets.

**Comment by softprops** [comment]
I do see the subtle potential for the case you mentioned here after reviewing the code

This action doesn't currently requery all active runs on each await cycle.

https://github.com/softprops/turnstyle/blob/b2c49cd5638e1140ffea6da9eacdda789bab1694/src/main.ts#L31

If I don't get to this sooner. I'd be happy to take a pull request to address that gap

**Comment by praneetloke** [comment]
@softprops I agree with your explanation in the first comment. In fact, that is what I expected this action would do. But as you said:

> This action doesn't currently requery all active runs on each await cycle.

I think that's what I am seeing instead.

> If I don't get to this sooner. I'd be happy to take a pull request to address that gap

Yep. I'll see if I can get to it soon as well.

**Comment by jeking3** [comment]
Thank you for publishing this solution!
