### ISSUE TITLE
Usage of set-output is deprecated

### ISSUE THREAD

**Issue by diamante0018** [softprops/turnstyle#42]
Hello, I'm using turnstyle in one of my GitHub workflows and I noticed I have been getting warnings about using the now deprecated command `set-output`.
This is the article by GitHub about this issue https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

I'm using turnstyle tag v1.

There is quite some time before the two commands are removed but I wanted to raise the issue with the maintainer(s) of this repository.
As I did some research, I noticed at https://github.com/actions/toolkit/blob/main/docs/commands.md that they still recommend using the now deprecated commands which I found quite puzzling but I digress.

Thanks for having a look.

**Comment by michaelstepner** [comment]
FYI, Github has incorporated equivalent functionality to turnstyle into the Github Actions spec using the 'concurrency' parameter. softprops/turnstyle was developed in 2020 and Github [added the concurrency parameter in 2021](https://github.blog/changelog/2021-04-19-github-actions-limit-workflow-run-or-job-concurrency/).

The native 'concurrency' implementation has additional features beyond what's possible in turnstyle, and it is lower cost: it leaves jobs pending rather than running while they wait for a previous job to end.

**Comment by diamante0018** [comment]
Thanks for letting me know.
I will use slowly but surely start using GitHub's native feature then 😃

**Comment by diamante0018** [comment]
I am happy with the native 'concurrency' implementations.
I will close this as I no longer need turnstyle to be updated.
🫡

Thanks
