### ISSUE TITLE
Node 12 deprecated

### ISSUE THREAD

**Issue by hkroger** [softprops/turnstyle#43]
Should this be updated to use node 16 as github is suggesting? 

https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

**Comment by fbuinosquy1985** [comment]
Please merge it.

**Comment by michaelstepner** [comment]
FYI, Github has incorporated equivalent functionality to turnstyle into the Github Actions spec using the 'concurrency' parameter. softprops/turnstyle was developed in 2020 and Github [added the concurrency parameter in 2021](https://github.blog/changelog/2021-04-19-github-actions-limit-workflow-run-or-job-concurrency/).

The native 'concurrency' implementation has additional features beyond what's possible in turnstyle, and it is lower cost: it leaves jobs pending rather than running while they wait for a previous job to end.

**Comment by jeherve** [comment]
I commented on the atttached PR but wanted to post this here as well for extra visibility.

While the `concurrency` parameter is useful, I'm afraid there are still situations[^1] where it isn't enough to catch potential duplicated runs. In those situations, `softprops/turnstyle` can still be useful.

Thanks!

[^1]: For reference, [here is one such case](https://github.com/Automattic/jetpack/issues/19099).

**Comment by anomiex** [comment]
More generally, GitHub's concurrency parameter handles the cases where you want existing runs (queued and optional the in-progress run too) to be cancelled when a new run comes in, but does not (yet) handle cases where you want runs to wait for in-progress runs without any being cancelled.

See https://github.com/orgs/community/discussions/5435 for one discussion asking for the feature (with GH replying "we hope to get to this someday").

**Comment by daimenworrall-cinch** [comment]
Hello! Are there any updates on this issue? Thanks!

**Comment by chenrui333** [comment]
Close as fixed. Thanks!
