### ISSUE TITLE
Isn't this still racy?

### ISSUE THREAD

**Issue by eguiraud** [softprops/turnstyle#6]
Hi,
thank you for making this action. I got here from https://github.community/t/serializing-workflow-runs-in-the-context-of-continuous-deployment -- really bad that github actions do not support this natively.

About the titular question: imagine turnstyle is blocking two workflows B and C as they wait for A to finish. If you are unlucky, B and C could both check at the same time whether a workflow with the target name is present. They might both find that A finished running a few seconds before. And they could both exit the loop, so B and C are now running concurrently.

Can that actually happen, or am I misunderstanding https://github.com/softprops/turnstyle/blob/master/src/main.ts ?

**Comment by softprops** [comment]
Thanks for reaching out

In short no. On every round of checking all active runs are resolved that have an run id less than thier own https://github.com/softprops/turnstyle/blob/64882c20d87df5b6d5c722af0e8c2206404a1f44/src/wait.ts#L42 i.e. anything that might be deploying first.

I'm your example since both B and C are active and B comes before C, so C will wait and B proceeds because there are no run ids less than B's at that point. The same can't be said for C.

**Comment by eguiraud** [comment]
Thank you for the clarification!
